### ISSUE TITLE
gitserver (git webhook server) eventually always fails

### ISSUE THREAD

**Issue by jonorthwash** [goavki/phenny#133]
After some time running, the git webhook server eventually stops.  It may be continuing to take requests, but the bot doesn't respond to them or push them to the channels.

`.gitserver status` also reports `Server is down! Start using '.gitserver start'`, but on `.gitserver start`, we find the address is still in use (`socket.error: [Errno 98] Address already in use (file "/usr/lib/python3.2/socketserver.py", line 430, in server_bind)`).

**Comment by jatinluthra14** [comment]
The problem is that The port is being used by other program. I've made it run using a port from the following page https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers 
So that it may not clash with it. It's working perfectly. It is still in observation. If it show the same error (not likely to expect now) then It can be easily fixed using SO_REUSEADDR and I'll submit the code as PR.

**Comment by jonorthwash** [comment]
No, it's not that it's in use by some other program (nothing on that list that might conflict is in use).  It seems to be that it's crashing (for an unknown reason—maybe it's receiving bad packets?) and not closing the port when it does.

So what I would like you to do:
1. Explain why `SO_REUSEADDR` might help.
2. Come up with some bad packets that you can test it with, and see if you can get the original version to crash.
3. Try to come up with a way to close the port if the module crashes, or at least some way to debug the crash.

**Comment by jonorthwash** [comment]
See comments in #258.

**Comment by Androbin** [comment]
There is a case where `SO_REUSEADDR` won't be enough.
See https://stackoverflow.com/a/6380198 for reference.
