### ISSUE TITLE
[More] add_messages > break_up logic is broken

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#281]
Method [`add_messages`](https://github.com/goavki/phenny/blob/master/modules/more.py#L28) in `modules/more.py` has defaulted parameter `break_up` which dictates how to split the messages to be added.
The default `break_up` logic is given by [`break_up_fn`](https://github.com/goavki/phenny/blob/master/modules/more.py#L10) which enforces the maximum message length of 430.
In part because [this line](https://github.com/goavki/phenny/blob/master/modules/more.py#L30) produces rubbish, most usages first `'\n'.join(x)` and then `x.split('\n')` as a work-around.
If we want to implement #159, we should address this first.

**Comment by Androbin** [comment]
@shardulc If you don't mind, I'd like to do this and two others in the next GCI task.

**Comment by shardulc** [comment]
@Androbin Sure, that works. Before you start, though, please demonstrate the faulty behavior.

**Comment by Androbin** [comment]
* if `msg` is a list `str(msg)` produces `['lorem ipsum', 'dolor sit amet']` and it'll print that literally!
* if `msg` is a string `str(msg)` is a no-op and it will just print the message.

The work-around works as follows:
* `'\n'.join(msgs)` produces a string which doesn't have the error.
* `msg.split('\n')` will give back the original list

The following problems arise:
* Individual messages may contain line breaks themselves and be broken apart.
* None of them will be split at the maximum message length.
* Without the work-around, the messages would be rubbish.
* It's cumbersome to implement for more modules.

**Comment by wei2912** [comment]
Default logic should split up any messages that exceed the maximum message
length. But such logic might already be implemented in bot.py. I'll check
and let you know soon.

**Comment by Androbin** [comment]
@wei2912 Now that you mention it:
https://github.com/goavki/phenny/blob/master/irc.py#L185

**Comment by Androbin** [comment]
Does this mean we can get rid of the break-up logic in the `more` module altogether?
This could even make for a more consistent `.more` behavior.

**Comment by wei2912** [comment]
I believe so, but please test it carefully.

The constant MAX_MSG_LEN should be retained (and in fact placed in the
config file for users to edit, and used in irc.py) in code determining how
to split certain messages. The default behaviour should be splitting by
spaces (as in irc.py), but certain modules may adopt alternative ways of
splitting.

The original reason for break_up_fn was to ensure that lines would be split
up by the max message length, I believe. This is because .more was intended
to send out *a single line*, so the message must be of at most 430
characters.

IMO, a better solution would be to leave the splitting up of lines to the
modules, and have them ensure that the maximum length is 430 characters.
So, there should not be any splitting of messages in the more module.

**Comment by shardulc** [comment]
> IMO, a better solution would be to leave the splitting up of lines to the modules, and have them ensure that the maximum length is 430 characters.

Actually I feel that having the break-up logic and the 430-character limit in `more` makes sense, so that modules can just use `more` whenever their messages are long. Otherwise, things passed to `phenny.msg` that are over 430 characters will just be truncated, encouraging someone to shift that module to `more`.

**Comment by wei2912** [comment]
They don't seem to be truncated. Rather, they are split up.

**Comment by Androbin** [comment]
* Splitting at spaces (like `break_up_fn`) is already done by `irc.py`
* Newlines are dropped by `irc.py` which was part of the reason for the work-around.
* If another module wants to do some custom splitting, it can do so before handing them over.
* PR #284 implements the newline splitting in `irc.py` next to the max-length splitting.

**Comment by shardulc** [comment]
What about:
 - `truncate` function from `git.py` moved to `tools.py`
 - `irc.py` uses that function blindly
 - `more.py` also uses that function, but takes care of lists of messages with newlines along with the queueing

**Comment by Androbin** [comment]
Wouldn't it be an unnecessary burden for modules to have to be constantly aware of their messages subject to truncating?
Your idea should be fine if we make `irc.py` split at newlines instead of dropping them altogether.

**Comment by Androbin** [comment]
See [#284](https://github.com/goavki/phenny/pull/284/files#diff-fc8ffb45857c1b6539f3506c6c16a515R175) for the latter.
