### ISSUE TITLE
more module not accounting for max_message_length

### ISSUE THREAD

**Issue by Androbin** [goavki/phenny#318]
[This line](https://github.com/goavki/phenny/blob/master/modules/more.py#L94) doesn't account for the fact that the given message might already be near the maximum message length.
This results in ugly message breaking. See https://github.com/goavki/phenny/pull/306#issuecomment-354682531 for reference.
@shardulc /cc

**Comment by shardulc** [comment]
Should not be hard to fix. Instead of using `break_up` at the full `max_message_length`, subtract the required number of characters (with a comment explaining why, of course), regardless of whether the "remaining" bit is going to be added or not. Test for messages greater than `max_message_length` and messages close to `max_message_length` will have to be added too.

**Comment by Androbin** [comment]
It's "not hard to fix" IF you know how it should behave.

But it's not that easy:
* We don't have a limit on the length of `(XXX remaining)` part
* Breaking is done on adding, `XXX` is known on retrieving

**Comment by Androbin** [comment]
Besides, we could potentially break other code calculating with `max_message_length`.

**Comment by shardulc** [comment]
> We don't have a limit on the length of `(XXX remaining)` part

Sure, not a hard limit, but it's a safe bet that it's never going to exceed 1000 messages?

> Breaking is done on adding, `XXX` is known on retrieving

Which is why I said "subtract the required number of characters ... regardless of whether the "remaining" bit is going to be added or not". I'm not saying the value of `max_message_length` should be globally changed, only locally for the `more` module. I.e. another argument to `break_up`.

**Comment by Androbin** [comment]
Still a bit hacky. Also, we'll have to maintain that number.

**Comment by Androbin** [comment]
Queuing, Saving and Retrieving should be independent of Displaying.

The current behavior as described in https://github.com/goavki/phenny/pull/277#issuecomment-353811741:
* If `count` is provided and is greater than 1, `X remaining messages` should be a separate message.
* Else, append `(X remaining)` to the single message that `.more` will output.

For `count == 1` (including implicit), we should do one of the following:
* Let `X remaining messages` be a separate message.
* Let `X remaining messages` be appended IF the resulting message is shorter than `max_message_length`, ELSE let it be a separate message.
* Just drop `X remaining messages`.

**Comment by Androbin** [comment]
@shardulc Can we agree on one of these variants?

**Comment by Androbin** [comment]
@shardulc Can we agree on one of these variants?

**Comment by shardulc** [comment]
> Let "X remaining messages" be appended IF the resulting message is shorter than `max_message_length`, ELSE let it be a separate message.

I think this works best.
